name: Build and Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy to EC2
      run: |
        # Set up SSH key for EC2 connection
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

        # Create the target directory on EC2 if it doesn't exist
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          mkdir -p /home/ubuntu/HelloWorldApp
        EOF

        # Copy the published files to EC2
        scp -r ./publish/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/HelloWorldApp

        # SSH into EC2 to configure and run the app
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Install .NET runtime if not already installed
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          wget https://packages.microsoft.com/config/ubuntu/20.04/prod.list
          sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y dotnet-runtime-6.0

          # Install and configure Nginx if not already installed
          sudo apt-get install -y nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx

          # Configure Nginx to proxy to the .NET app
          sudo bash -c 'cat > /etc/nginx/sites-available/HelloWorldApp << "EOF"
          server {
              listen 80;
              server_name ${{ secrets.EC2_HOST }};

              location / {
                  proxy_pass http://localhost:5000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
          }
          EOF'

          sudo ln -s /etc/nginx/sites-available/HelloWorldApp /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl restart nginx

          # Navigate to the app directory
          cd /home/ubuntu/HelloWorldApp

          # Run the app on port 5000
          nohup dotnet HelloWorldApp.dll --urls http://0.0.0.0:5000 &
        EOF
