name: Build and Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # Ensure that this version is correctly set to .NET 6.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the Blazor WebAssembly app
      run: dotnet build --configuration Release

    - name: Publish the Blazor WebAssembly app
      run: dotnet publish -c Release -o ./publish

    - name: List files in publish directory
      run: |
        ls -R ./publish

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ftpupload.net         # FTP server address
        username: ${{ secrets.FTP_USER }}          # FTP username
        password: ${{ secrets.FTP_PASS }}          # FTP password
        local-dir: './publish/wwwroot/'           # Path to static files (from .NET publish)
        server-dir: '/htdocs/'                     # Destination directory on FTP server
        protocol: 'ftps'                            # Protocol (use 'ftps' for secure FTP)
        log-level: 'verbose'                       # Set log level to 'verbose' for detailed output
